version: 2
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: SettingsSentry

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: settingssentry

archives:
  - format: zip
    name_template: |-
      {{ .ProjectName }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - configs/**        # Include everything in configs...
      - "!configs/TestCommand.cfg" # ...except this specific file
checksum: # Correct indentation
  name_template: 'checksums.txt'


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
