project_name: SettingsSentry

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: SettingsSentry

archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - configs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - name: settingssentry
    tap:
      owner: sstraus
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/sstraus/SettingsSentry
    description: Securely archive and reinstate your macOS application configurations
    license: MIT
    test: |
      system "#{bin}/SettingsSentry --version"
    install: |
      bin.install "SettingsSentry"
