name: Generate Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.go'
      - '**.md'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

jobs:
  docs:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install godoc
        run: go install golang.org/x/tools/cmd/godoc@latest

      - name: Generate API documentation
        run: |
          mkdir -p docs/api
          godoc -url=/pkg/SettingsSentry/ > docs/api/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
