name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          check-latest: true

      - name: Run tests
        run: go test -v ./...

      - name: Build macOS binary
        run: |
          go build -o SettingsSentry
          chmod +x SettingsSentry
          
      - name: Create DMG
        run: |
          mkdir -p ./SettingsSentry.app/Contents/MacOS
          cp SettingsSentry ./SettingsSentry.app/Contents/MacOS/
          hdiutil create -volname "SettingsSentry" -srcfolder ./SettingsSentry.app -ov -format UDZO SettingsSentry.dmg

      - name: Create ZIP with configs
        run: |
          zip -r SettingsSentry.zip SettingsSentry configs

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
